import React, { useMemo, useState } from "react";

const ROLES = ["Customer Support Advisor", "Sales Executive", "Account Manager", "Software Engineer", "Product Manager", "Finance Analyst", "Marketing Executive", "Operations", "Other"];
const DEPARTMENTS = ["Customer Support", "Sales", "Engineering", "Product", "Marketing", "Finance", "Operations", "HR", "Other"];
const BUSINESS_AREAS = ["Payments", "Customer Portal", "CRM", "Authentication", "Website", "Retail", "Infrastructure", "Internal Systems", "Other"];
const REPORT_SOURCES = ["Internal portal", "Slack", "Microsoft Teams", "Email", "Phone", "Monitoring alert", "Meeting", "Other"];

const THEME = { pageBg:"#F5F8FC", cardBg:"#FFFFFF", cardBorder:"#D8E3EC", subtleBorder:"#E4EBF2", text:"#1F2937", heading:"#0F172A", subtleText:"#64748B", inputBorder:"#CBD5E1", primaryBg:"#2563EB", primaryBgHover:"#1D4ED8", successBg:"#ECFDF5", successBorder:"#A7F3D0", successText:"#065F46", warningBg:"#FFFBEB", warningBorder:"#FCD34D", warningText:"#92400E", dangerBg:"#FEF2F2", dangerBorder:"#FCA5A5", dangerText:"#B91C1C", shadow:"0 12px 32px rgba(15,23,42,0.08)" };

function FieldLabel({ children, required=false }) { return <label style={{display:"block",marginBottom:6,fontSize:13,fontWeight:750,color:THEME.heading}}>{children}{required?<span style={{color:"#DC2626"}}> *</span>:null}</label>; }
function inputStyle(){return {width:"100%",boxSizing:"border-box",padding:"10px 12px",borderRadius:10,border:`1px solid ${THEME.inputBorder}`,background:"#FFFFFF",color:THEME.text,fontSize:14,outline:"none"};}
function BrandHeader({onOpenDashboard}){return <header className="oth-report-header" style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",gap:20,paddingBottom:16,borderBottom:`1px solid ${THEME.subtleBorder}`}}><div><div style={{fontSize:26,lineHeight:1.1,fontWeight:900,color:THEME.heading,letterSpacing:"-0.02em"}}>Ops Triage Hub</div><div style={{marginTop:5,fontSize:13,fontWeight:800,color:"#2563EB",letterSpacing:"0.04em",textTransform:"uppercase"}}>Operational Decision Support</div></div><button type="button" onClick={onOpenDashboard} style={{padding:"10px 14px",borderRadius:10,border:"1px solid #2563EB",background:"#FFFFFF",color:"#2563EB",fontWeight:800,cursor:"pointer",whiteSpace:"nowrap"}}>Operations Dashboard</button></header>}

export default function ReportOperationalIssue({onOpenDashboard}){
  const [reporterName,setReporterName]=useState(""); const [role,setRole]=useState(ROLES[0]); const [department,setDepartment]=useState(DEPARTMENTS[0]); const [contact,setContact]=useState("");
  const [reportSource,setReportSource]=useState(REPORT_SOURCES[0]); const [sourceReference,setSourceReference]=useState(""); const [originalReport,setOriginalReport]=useState("");
  const [title,setTitle]=useState(""); const [description,setDescription]=useState(""); const [businessArea,setBusinessArea]=useState(BUSINESS_AREAS[0]); const [attention,setAttention]=useState("standard");
  const [submitting,setSubmitting]=useState(false); const [phase,setPhase]=useState(""); const [error,setError]=useState(""); const [submitted,setSubmitted]=useState(null);
  const validation = useMemo(() => {
    const trimmedOriginalReport = originalReport.trim();
    const urlOnly = /^(https?:\/\/|www\.)\S+$/i.test(trimmedOriginalReport);

    return {
      reporterName: reporterName.trim().length >= 2,
      contact: contact.trim().length >= 3,
      title: title.trim().length >= 10,
      description: description.trim().length >= 30,
      originalReport: trimmedOriginalReport.length >= 20 && !urlOnly,
      role: Boolean(role),
      department: Boolean(department),
      businessArea: Boolean(businessArea),
      reportSource: Boolean(reportSource),
    };
  }, [reporterName, contact, title, description, originalReport, role, department, businessArea, reportSource]);

  const valid = useMemo(() => Object.values(validation).every(Boolean), [validation]);

  async function submitIssue(event){event.preventDefault(); if(!valid||submitting)return; setSubmitting(true);setError("");setPhase("Recording incident…");
    try{
      const request=fetch("/api/incidents",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:title.trim(),description:description.trim(),priority:attention==="critical"?"P1":"P2",reporter_name:reporterName.trim(),reporter_role:role,reporter_department:department,reporter_contact:contact.trim(),report_source:reportSource,source_reference:sourceReference.trim(),original_report:originalReport.trim(),business_area:businessArea,reporter_attention:attention})});
      setTimeout(()=>setPhase("Reviewing operational context…"),250);
      const response=await request; const text=await response.text(); let data; try{data=JSON.parse(text)}catch{data=text}
      if(!response.ok){const message=data&&typeof data==="object"&&data.detail?(typeof data.detail==="string"?data.detail:JSON.stringify(data.detail)):typeof data==="string"?data:"Unable to report the operational issue.";throw new Error(message)}
      setSubmitted({id:data?.id||"",title:title.trim(),reporterName:reporterName.trim(),triage:data?.initial_triage||null,triageSource:data?.initial_triage_source||""}); setPhase("");
    }catch(e){setError(e.message||"Unable to report the operational issue.");setPhase("");}finally{setSubmitting(false)}
  }
  function resetForm(){setReporterName("");setRole(ROLES[0]);setDepartment(DEPARTMENTS[0]);setContact("");setReportSource(REPORT_SOURCES[0]);setSourceReference("");setOriginalReport("");setTitle("");setDescription("");setBusinessArea(BUSINESS_AREAS[0]);setAttention("standard");setError("");setSubmitted(null);setPhase("");}
  const triage=submitted?.triage;
  return <div className="oth-report-page" style={{minHeight:"100vh",background:THEME.pageBg,color:THEME.text}}><div className="oth-report-container"><BrandHeader onOpenDashboard={onOpenDashboard}/><main style={{marginTop:20}}>
    {submitted?<section style={{padding:24,borderRadius:18,border:`1px solid ${THEME.successBorder}`,background:THEME.successBg,boxShadow:THEME.shadow}}><div style={{fontSize:26,fontWeight:900,color:THEME.heading}}>Operational issue reported</div><p style={{margin:"8px 0 0",color:THEME.successText}}><strong>{submitted.title}</strong> has been recorded successfully. Reference: <strong>{submitted.id}</strong></p>
      {triage?<div style={{marginTop:18,padding:18,borderRadius:14,border:"1px solid #BFDBFE",background:"#FFFFFF"}}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div style={{fontSize:12,fontWeight:850,color:"#2563EB",textTransform:"uppercase",letterSpacing:"0.04em"}}>Initial operational review</div><div style={{marginTop:5,fontSize:13,color:THEME.subtleText}}>AI-assisted recommendation · Operations confirmation required</div></div><div style={{fontWeight:900,color:THEME.heading}}>Suggested priority: {triage.suggested_priority||"Review"}</div></div>
      <div style={{marginTop:14,fontWeight:850,color:THEME.heading}}>{triage.operational_risk||"Operations review required."}</div><div style={{marginTop:8,fontSize:13,lineHeight:1.55,color:THEME.text}}>{triage.reason}</div><div style={{marginTop:12,fontSize:12,fontWeight:800,color:THEME.subtleText}}>Suggested first action</div><div style={{marginTop:4,fontSize:13}}>{triage.suggested_first_action||"Review the incident evidence."}</div>
      {Array.isArray(triage.missing_information)&&triage.missing_information.length?<div style={{marginTop:12}}><div style={{fontSize:12,fontWeight:800,color:THEME.subtleText}}>Additional information that may help Operations</div>{triage.missing_information.map((x,i)=><div key={i} style={{marginTop:5,fontSize:13}}>• {x}</div>)}</div>:null}<div style={{marginTop:12,fontSize:11,color:THEME.subtleText}}>Review source: {submitted.triageSource||"Recorded assessment"}</div></div>:null}
      <div style={{marginTop:18,display:"flex",gap:10,flexWrap:"wrap"}}><button type="button" onClick={onOpenDashboard} style={{padding:"11px 16px",borderRadius:10,border:"2px solid #2563EB",background:THEME.primaryBg,color:"#FFF",fontWeight:850,cursor:"pointer"}}>Open Operations Dashboard</button><button type="button" onClick={resetForm} style={{padding:"11px 16px",borderRadius:10,border:"1px solid #2563EB",background:"#FFF",color:"#2563EB",fontWeight:800,cursor:"pointer"}}>Report another issue</button></div></section>:
    <><section style={{marginBottom:14}}><div style={{display:"inline-flex",padding:"5px 9px",borderRadius:999,border:"1px solid #BFDBFE",background:"#EFF6FF",color:"#1D4ED8",fontSize:12,fontWeight:800}}>Internal reporting portal</div><h1 style={{margin:"9px 0 0",fontSize:30,lineHeight:1.15,color:THEME.heading}}>Report Operational Issue</h1><p style={{margin:"6px 0 0",maxWidth:760,lineHeight:1.55,color:THEME.subtleText}}>Record what was reported, where it came from and the operational context known at this point. Operations will confirm priority and coordinate the response.</p></section>
    <form onSubmit={submitIssue}><div style={{border:`1px solid ${THEME.cardBorder}`,borderRadius:18,background:THEME.cardBg,boxShadow:THEME.shadow,overflow:"hidden"}}>
      <section style={{padding:16}}><h2 style={{margin:0,fontSize:17,color:THEME.heading}}>Who reported this?</h2><div className="oth-intake-grid-four" style={{marginTop:11}}><div><FieldLabel required>Full Name</FieldLabel><input value={reporterName} onChange={e=>setReporterName(e.target.value)} placeholder="e.g. Sarah Jones" style={inputStyle()}/></div><div><FieldLabel required>Role</FieldLabel><select value={role} onChange={e=>setRole(e.target.value)} style={inputStyle()}>{ROLES.map(x=><option key={x}>{x}</option>)}</select></div><div><FieldLabel required>Department</FieldLabel><select value={department} onChange={e=>setDepartment(e.target.value)} style={inputStyle()}>{DEPARTMENTS.map(x=><option key={x}>{x}</option>)}</select></div><div><FieldLabel required>Contact</FieldLabel><input value={contact} onChange={e=>setContact(e.target.value)} placeholder="Email, phone or Slack" style={inputStyle()}/></div></div></section>
      <section style={{padding:16,borderTop:`1px solid ${THEME.subtleBorder}`}}><h2 style={{margin:0,fontSize:17,color:THEME.heading}}>Where did this come from?</h2><div className="oth-intake-source-grid" style={{marginTop:11}}><div><FieldLabel required>Source</FieldLabel><select value={reportSource} onChange={e=>setReportSource(e.target.value)} style={inputStyle()}>{REPORT_SOURCES.map(x=><option key={x}>{x}</option>)}</select></div><div><FieldLabel>Source reference</FieldLabel><input value={sourceReference} onChange={e=>setSourceReference(e.target.value)} placeholder="Thread, email subject, alert ID, phone number…" style={inputStyle()}/></div></div><div style={{marginTop:10}}><FieldLabel required>Original report or message</FieldLabel><textarea value={originalReport} onChange={e=>setOriginalReport(e.target.value)} rows={2} placeholder="Paste the original Slack/email/alert text, or record what was said on the call or in the meeting." style={{...inputStyle(),resize:"vertical",lineHeight:1.45,borderColor:originalReport.length>0&&!validation.originalReport?THEME.dangerBorder:THEME.inputBorder}}/>{originalReport.length>0&&!validation.originalReport?<div style={{marginTop:5,fontSize:12,color:THEME.dangerText}}>Enter the original report or message itself (at least 20 characters). A link alone belongs in Source reference.</div>:null}</div></section>
      <section style={{padding:16,borderTop:`1px solid ${THEME.subtleBorder}`}}><h2 style={{margin:0,fontSize:17,color:THEME.heading}}>What is happening?</h2><div style={{marginTop:11,display:"grid",gap:10}}><div><FieldLabel required>Issue Title</FieldLabel><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Retail payment card readers offline across 124 stores" style={{...inputStyle(),borderColor:title.length>0&&!validation.title?THEME.dangerBorder:THEME.inputBorder}}/>{title.length>0&&!validation.title?<div style={{marginTop:5,fontSize:12,color:THEME.dangerText}}>Enter a meaningful issue title (at least 10 characters).</div>:null}</div><div><FieldLabel required>Description</FieldLabel><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="Describe what is known in natural language. Include timing, affected customers or teams, symptoms and any known workaround." style={{...inputStyle(),resize:"vertical",lineHeight:1.45,borderColor:description.length>0&&!validation.description?THEME.dangerBorder:THEME.inputBorder}}/>{description.length>0&&!validation.description?<div style={{marginTop:5,fontSize:12,color:THEME.dangerText}}>Add enough operational context to describe the issue (at least 30 characters).</div>:null}</div><div style={{maxWidth:360}}><FieldLabel required>Business Area</FieldLabel><select value={businessArea} onChange={e=>setBusinessArea(e.target.value)} style={inputStyle()}>{BUSINESS_AREAS.map(x=><option key={x}>{x}</option>)}</select></div></div></section>
      <section style={{padding:16,borderTop:`1px solid ${THEME.subtleBorder}`}}><h2 style={{margin:0,fontSize:17,color:THEME.heading}}>Reporter-assessed urgency</h2><div className="oth-intake-attention-grid" style={{marginTop:10}}>{[{value:"standard",title:"Standard",description:"Operations should review and prioritise the issue."},{value:"critical",title:"Critical",description:"The reporter believes immediate review may be required."}].map(o=>{const selected=attention===o.value;return <label key={o.value} style={{display:"grid",gridTemplateColumns:"22px 1fr",gap:10,padding:10,borderRadius:12,border:selected?"2px solid #2563EB":`1px solid ${THEME.inputBorder}`,background:selected?"#EFF6FF":"#FFF",cursor:"pointer"}}><input type="radio" checked={selected} onChange={()=>setAttention(o.value)} style={{marginTop:3}}/><span><span style={{display:"block",fontWeight:850,color:THEME.heading}}>{o.title}</span><span style={{display:"block",marginTop:3,fontSize:12,color:THEME.subtleText}}>{o.description}</span></span></label>})}</div>
        <div style={{marginTop:10,padding:"9px 11px",borderRadius:10,border:"1px solid #FCD34D",background:"#FFFBEB",fontSize:12,lineHeight:1.45,color:"#92400E"}}>
          <strong>Use Critical only when immediate operational review may be required</strong> due to significant customer, revenue, service or business impact. Operations will confirm the final priority.
        </div>
      </section>
      <section style={{padding:14,borderTop:`1px solid ${THEME.subtleBorder}`,background:"#F8FAFC"}}>{error?<div style={{marginBottom:10,padding:10,borderRadius:10,border:`1px solid ${THEME.dangerBorder}`,background:THEME.dangerBg,color:THEME.dangerText,fontSize:13}}>{error}</div>:null}{submitting?<div className="oth-triage-loading" style={{marginBottom:10}}><div className="oth-triage-skeleton"/><div style={{fontSize:13,fontWeight:800,color:"#1D4ED8"}}>{phase||"Reviewing operational context…"}</div></div>:null}<button type="submit" disabled={!valid||submitting} style={{width:"100%",padding:"12px 16px",borderRadius:10,border:!valid||submitting?"1px solid #D9E2EC":"2px solid #2563EB",background:!valid||submitting?"#E9EEF5":THEME.primaryBg,color:!valid||submitting?"#94A3B8":"#FFF",fontWeight:900,cursor:!valid||submitting?"not-allowed":"pointer"}}>{submitting?"Reporting issue…":"Report Operational Issue"}</button>{!valid?<div style={{marginTop:7,textAlign:"center",fontSize:12,color:THEME.subtleText}}>Complete all required fields with enough detail to submit the issue.</div>:null}</section>
    </div></form></>}
  </main></div></div>
}